[package]
name = "mail-parser-wasm"
version = "0.2.1"
edition = "2021"
description = "A simple mail parser for wasm"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
mail-parser = "0.9.4"
wasm-bindgen = "0.2.99"
